-- AlterTable
ALTER TABLE "words" ALTER COLUMN "phonetic" DROP DEFAULT,
ALTER COLUMN "audio" DROP DEFAULT,
ALTER COLUMN "example" DROP DEFAULT,
ALTER COLUMN "topic" DROP DEFAULT,
ALTER COLUMN "partOfSpeech" DROP DEFAULT;
